- name: Manage S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Create an S3 bucket
      amazon.aws.s3_bucket:
        name: my-new-bucket
        state: present
        region: eu-west-1
        acl: private
        tags:
          Environment: Dev
          Owner: Admin
      register: result

    - name: Debug the result
      debug:
        var: result
