- name: Launch EC2 t3.medium with EBS 50GB and execute setup script
  hosts: localhost
  gather_facts: false
  connection: local


  tasks:
- name: Launch EC2 t3.medium with EBS 50GB and execute setup script
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    instance_type: t2.micro
    key_name: my-ec2-key
    security_group: ansible-security-group
    region: us-east-1
    ebs_volume_size: 50
    ami: ami-0e86e20dae9224db8


  tasks:

  - name: Create security group
    amazon.aws.ec2_security_group:
      name: "{{ security_group }}"
      description: "Security group for Ansible-managed EC2 instances"
      region: "{{ region }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: "0.0.0.0/0"
      rules_egress:
      - from_port: 0
        to_port: 0
        proto: all
        cidr_ip: "0.0.0.0/0"
      state: present
    register: sg

  - name: Launch EC2 instance with 50GB EBS and setup script
    amazon.aws.ec2_instance:
      name: Ansible-Managed-EC2
      key_name: key1
      security_groups:
      - "{{ sg.group_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami }}"
      region: "{{ region }}"
      wait: yes
      tags:
        Name: Ansible-Managed-EC2
    register: ec2_instance





