- name: Launch EC2 t3.medium with EBS 50GB and execute setup script
  hosts: localhost
  gather_facts: false
  connection: local


  tasks:
  - name: Create EBS volume
    amazon.aws.ec2_vol:
      name: first-volume
      volume_size: 50
      volume_type: gp3
      region: us-east-1
      zone: us-east-1a
      device_name: /dev/sda2
    register: ebs_volume



