- name: Update EC2 instance
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:
  - name: Update EC2 instance type and tags
    amazon.aws.ec2_instance:
      region: us-east-1
      instance_ids: "{{ INSTANCE_ID }}"
      instance_type: t3.medium
      tags:
        Name: UpdatedInstance3
    register: updated_instance

  - name: Display updated instance details
    debug:
      msg: "{{ updated_instance }}"
